AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyDashApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.server
      Runtime: python3.8
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /
            Method: get